AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for lambda function build and packaging

Resources:
  IndexDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: index_data/
      Handler: app.lambda_handler
      Runtime: python2.7

  DeleteDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_data/
      Handler: app.lambda_handler
      Runtime: python2.7

  RetentionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: retention/
      Handler: app.lambda_handler
      Runtime: python2.7
